name: Run DingTalk Robot and Send Message

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker environment
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        SECRET: ${{ secrets.SECRET }}
      run: |
        docker run -d --name dingtalk-robot --restart=unless-stopped -p 8080:8080 \
          -e ACCESS_TOKEN="$ACCESS_TOKEN" \
          -e SECRET="$SECRET" \
          -e LOG_LEVEL="info" \
          jerryin/dingtalk-robot

    - name: Wait for DingTalk Robot to start
      run: |
        sleep 1s

    - name: Send message using DingTalk Robot
      run: |
        curl -X POST 'http://localhost:8080/robot/send' -H 'Content-Type: application/json' -d '{"markdown":{"title":"${{ github.repository }}","text":"${{ github.event.head_commit.message }}"}}'