name: DingTalk Notification with Signature

on:
  push:
    branches: [ main ]

jobs:
  dingtalk-notification:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: DingTalk Notification with Signature
      run: |
        pip install requests
        ls
        python ../.github/workflows/dingtalk_notify.py
      env:
        DINGTALK_WEBHOOK: ${{ secrets.DINGTALK_WEBHOOK }}
        DINGTALK_SECRET: ${{ secrets.DINGTALK_SECRET }}